import type { Metadata } from 'next'
import '@/styles/globals.css'
import { ApolloClientProvider } from '@/providers/ApolloClientProvider'
import { NextIntlClientProvider } from 'next-intl'
import { getLocale, getMessages } from 'next-intl/server'
import { cn } from '@/utils/tw-merge'
import { GeistSans } from 'geist/font/sans'
import { ThemeProvider } from '@/providers/ThemeProvider'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default async function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	const locale = await getLocale()
	const messages = await getMessages()
	return (
		<html lang={locale}>
			<body className={GeistSans.variable}>
				<ApolloClientProvider>
					<NextIntlClientProvider messages={messages} locale={locale}>
						<ThemeProvider
							attribute='class'
							defaultTheme='dark'
							disableTransitionOnChange
						>
							{children}
						</ThemeProvider>
					</NextIntlClientProvider>
				</ApolloClientProvider>
			</body>
		</html>
	)
}
