services:
  db:
    container_name: twithcopy-db
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - twithcopy-backend

  redis:
    container_name: twithcopy-redis
    image: redis:5.0
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - twithcopy-backend
volumes:
  postgres_data:
  redis_data:

networks:
  twithcopy-backend:
